### ISSUE TITLE
Bug - Changing your Display Settings Crashes your game

### ISSUE THREAD

**Issue by GracieLovelight** [PLAYER-ZER0-STUDIO/Toontown-Fantasy#44]
Changing your Display Settings will crash your game, leaving behind this error message:

```Traceback (most recent call last):
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\otp\launcher\LauncherBase.py", line 161, in mainLoop
    self._runTaskManager()
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\otp\launcher\LauncherBase.py", line 141, in _runTaskManager
    taskMgr.run()
  File "C:\Open-Panda\direct\task\Task.py", line 541, in run
    self.step()
  File "C:\Open-Panda\direct\task\Task.py", line 492, in step
    self.mgr.poll()
  File "C:\Open-Panda\direct\showbase\EventManager.py", line 50, in eventLoopTask
    self.doEvents()
  File "C:\Open-Panda\direct\showbase\EventManager.py", line 44, in doEvents
    processFunc(dequeueFunc())
  File "C:\Open-Panda\direct\showbase\EventManager.py", line 100, in processEvent
    messenger.send(eventName, paramList)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 335, in send
    self.__dispatch(acceptorDict, event, sentArgs, foundWatch)
  File "C:\Open-Panda\direct\showbase\Messenger.py", line 420, in __dispatch
    result = method (*(extraArgs + sentArgs))
  File "C:\Open-Panda\direct\gui\DirectButton.py", line 107, in commandFunc
    self['command'](*self['extraArgs'])
  File "C:\Open-Panda\direct\gui\DirectDialog.py", line 180, in <lambda>
    command = lambda s = self, v = value: s.buttonCommand(v)
  File "C:\Open-Panda\direct\gui\DirectDialog.py", line 339, in buttonCommand
    self['command'](value, *self['extraArgs'])
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\DisplaySettingsDialog.py", line 464, in __applyDone
    if not self.changeDisplayProperties(
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\DisplaySettingsDialog.py", line 521, in changeDisplayProperties
    if self.resetDisplayProperties(pipe, properties):
  File "E:\Toontown\Toontown Fantasy\Toontown-Fantasy\toontown\shtiker\DisplaySettingsDialog.py", line 627, in resetDisplayProperties
    NametagGlobals.setCamera(base.cam)
NameError: name 'NametagGlobals' is not defined
Press any key to continue . . .```

**Comment by GracieLovelight** [comment]
This has been patched.
